backend:
  name: github
  repo: vstanyshevskyy/vpershe
  branch: social-icons

media_folder: "static/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: blog
    label: Статті
    folder: "content/articles"
    create: true
    fields:
      - {label: "Type", name: "contentType", widget: "string", default: "articles"}
      - {label: "Url", name: "path", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Підзаголовок", name: "subtitle", widget: "string"}
      - {label: "Фото для привернення уваги", name: "image", widget: "image", required: false}
      - {label: "Категорія", name: "category", widget: "string"}
      - label: "Теги"
        name: "tags"
        widget: "list"    
        default: ["статті", "едукація"] 
      - {label: "Текст", name: "body", widget: "markdown"}
      - {label: "Час публікації", name: "publishTime", widget: "datetime"}
      - {label: "Meta Title", name: "metaTitle", widget: "string", required: false }
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
  - name: settings
    label: Налаштування
    files:
      - label: "Футер"
        name: "footer"
        file: "content/settings/footer.md"
        fields:
          - name: "contentType"
            widget: "hidden"
            default: "footer_settings"
          - label: "Блоки"
            name: "blocks"
            widget: "list"
            fields:
              - {label: Заголовок, name: title, widget: string, default: ""}
              - {label: Контент, name: content, widget: markdown, default: ""}
          - label: "Копірайт"
            name: "copyrightText"
            widget: "string"
          - label: "Посилання в самому низу"
            name: "bottomLinks"
            widget: "list"
            fields:
              - {label: Текст, name: text, widget: string, default: ""}
              - {label: URL, name: url, widget: string, default: ""}
      - label: "Навігація"
        name: "navbar"
        file: "content/settings/navbar.md"
        fields:
          - name: "contentType"
            widget: "hidden"
            default: "navbar_settings"
          - label: "Меню"
            name: "links"
            widget: "list"
            fields:
              - label: "Текст"
                name: "text"
                widget: "string"
              - label: "Посилання"
                name: "url"
                widget: "string"
          - label: "Соцмережі"
            name: "socialIcons"
            widget: "list"
            fields:
              - label: "Мережа"
                name: "type"
                widget: "select"
                options: ["Facebook", "Twitter", "Instagram", "Google Plus"]
              - label: "Посилання"
                name: "url"
                widget: "string"