backend:
  name: github
  repo: vstanyshevskyy/vpershe
  branch: style-guide

media_folder: "static/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: articles
    label: Статті
    folder: "content/articles"
    create: true
    fields:
      - {label: "Type", name: "contentType", widget: "hidden", default: "articles"}
      - {label: "Url", name: "path", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Підзаголовок", name: "subtitle", widget: "string"}
      - {label: "Фото", name: "image", widget: "image", required: false}
      - {label: "Додати до каруселі на головній", name: "carousel_featured", widget: "boolean", required: false}
      - {label: "Фото для каруселі на головній (170*170)", name: "carousel_image", widget: "image", required: false}
      - {label: "Фото для списку (533*332)", name: "list_image", widget: "image", required: false}
      - label: "Теги"
        name: "tags"
        widget: "list"    
        default: [] 
      - {label: "Текст", name: "body", widget: "markdown"}
      - {label: "Час публікації", name: "publishTime", widget: "datetime"}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
  - name: stories
    label: Історії
    folder: "content/stories"
    create: true
    fields:
      - {label: "Type", name: "contentType", widget: "hidden", default: "stories"}
      - {label: "Url", name: "path", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Підзаголовок", name: "subtitle", widget: "string"}
      - {label: "Фото", name: "image", widget: "image", required: false}
      - {label: "Додати до каруселі на головній", name: "carousel_featured", widget: "boolean", required: false}
      - {label: "Фото для каруселі на головній (170*170)", name: "carousel_image", widget: "image", required: false}
      - {label: "Фото для списку (250*250)", name: "list_image", widget: "image", required: false}
      - label: "Теги"
        name: "tags"
        widget: "list"    
        default: [] 
      - {label: "Текст", name: "body", widget: "markdown"}
      - {label: "Час публікації", name: "publishTime", widget: "datetime"}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
  - name: sexoteca
    label: Сексотека
    folder: "content/sexoteca"
    create: true
    fields:
      - {label: "Type", name: "contentType", widget: "hidden", default: "sexoteca"}
      - {label: "Url", name: "path", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Підзаголовок", name: "subtitle", widget: "string"}
      - {label: "Фото", name: "image", widget: "image", required: false}
      - {label: "Додати до каруселі на головній", name: "carousel_featured", widget: "boolean", required: false}
      - {label: "Фото для каруселі на головній (170*170)", name: "carousel_image", widget: "image", required: false}
      - {label: "Фото для списку (250*250)", name: "list_image", widget: "image", required: false}
      - label: "Теги"
        name: "tags"
        widget: "list"    
        default: [] 
      - {label: "Текст", name: "body", widget: "markdown"}
      - {label: "Час публікації", name: "publishTime", widget: "datetime"}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
  - name: advice
    label: Поради
    folder: "content/advice"
    create: true
    fields:
      - {label: "Type", name: "contentType", widget: "hidden", default: "advice"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}
      - label: "Теги"
        name: "tags"
        widget: "list"    
        default: [] 
      - {label: "Час публікації", name: "publishTime", widget: "datetime"}
  - name: settings
    label: Налаштування
    files:
      - label: 'Загальні'
        name: 'general'
        file: 'content/settings/general.md'
        fields:
          - name: 'contentType'
            widget: 'hidden'
            default: 'general_settings'
          - label: 'favicon'
            name: 'favicon'
            widget: image
          - label: 'URL сайту'
            name: 'url'
            widget: string
          - label: 'Назва організації, від імені якої постимо контент'
            name: 'organizationTitle'
            widget: string
          - label: 'Автор по замовчуванню'
            name: 'defaultAuthor'
            widget: string
          - label: 'Фото автора по замовчуванню'
            name: 'defaultAuthorImage'
            widget: image
          - label: 'Title (Текст заголовку вікна браузера на головній)'
            name: 'title'
            widget: string
          - label: 'Title template (формат для заголовку інших сторінок)'
            name: 'titleTemplate'
            widget: string
          - label: 'Meta Description'
            name: 'metaDescription'
            widget: string
          - label: 'Meta Keywords'
            name: 'metaKeywords'
            widget: string
          - label: 'FB Title (цей текст показуватиме ФБ при шерінгу сторінки)'
            name: 'fbTitle'
            widget: string
          - label: 'FB Description'
            name: 'fbDescription'
            widget: string
          - label: 'FB Image'
            name: 'fbImage'
            widget: image
      - label: 'Головна сторінка'
        name: 'homepage'
        file: 'content/settings/homepage.md'
        fields:
          - name: 'contentType'
            widget: 'hidden'
            default: 'homepage_settings'
          - label: 'Про проект'
            name: 'body'
            widget: 'markdown'
          - label: 'Email для форми'
            name: 'contactFormEmail'
            widget: 'string'
          - label: 'Заголовок форми'
            name: 'contactFormTitle'
            widget: 'string'
      - label: "Футер"
        name: "footer"
        file: "content/settings/footer.md"
        fields:
          - name: "contentType"
            widget: "hidden"
            default: "footer_settings"
          - label: "Блоки"
            name: "blocks"
            widget: "list"
            fields:
              - {label: Заголовок, name: title, widget: string, default: ""}
              - {label: Контент, name: content, widget: markdown, default: ""}
          - label: "Копірайт"
            name: "copyrightText"
            widget: "string"
          - label: "Посилання в самому низу"
            name: "bottomLinks"
            widget: "list"
            fields:
              - {label: Текст, name: text, widget: string, default: ""}
              - {label: URL, name: url, widget: string, default: ""}
      - label: "Навігація"
        name: "navbar"
        file: "content/settings/navbar.md"
        fields:
          - name: "contentType"
            widget: "hidden"
            default: "navbar_settings"
          - label: "Меню"
            name: "links"
            widget: "list"
            fields:
              - label: "Текст"
                name: "text"
                widget: "string"
              - label: "Посилання"
                name: "url"
                widget: "string"
          - label: "Соцмережі"
            name: "socialIcons"
            widget: "list"
            fields:
              - label: "Мережа"
                name: "type"
                widget: "select"
                options: ["Facebook", "Twitter", "Instagram", "Google Plus"]
              - label: "Посилання"
                name: "url"
                widget: "string"