backend:
  name: github
  repo: vstanyshevskyy/vpershe

media_folder: static/assets

collections:
  - name: blog
    label: Статті
    folder: articles
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - label: "Теги"
        name: "tags"
        widget: "list"    
        field:
          - {label: Тег, name: tag, widget: string}     
      - {label: "Текст", name: "body", widget: "markdown"}
      - {label: "Час публікації", name: "publishTime", widget: "datetime"}
    